### Global Variables
@baseUrl = http://localhost:3000
@apiPrefix = /api/v1
@authToken = <your_token_here>
@productId = eewo7b1dy57ixeda9yy2bge5
@organizationId = test
@userId = test
@email = test@gmail.com
@orgId = test

##################################################################
# SYSTEM ROUTES
##################################################################

# @name healthCheck
GET {{baseUrl}}/api/health
Content-Type: application/json

###

# @name getRSS
GET {{baseUrl}}/app/rss.xml
Content-Type: application/json

##################################################################
# AUTH ROUTES
##################################################################

# @name login
POST {{baseUrl}}{{apiPrefix}}/auth/login
Content-Type: application/json

{
    "email": "doavers@gmail.com",
    "password": "password123"
}

###

# @name register
POST {{baseUrl}}{{apiPrefix}}/auth/register
Content-Type: application/json

{
    "name": "New User",
    "email": "newuser@example.com",
    "password": "password123",
    "role": "user"
}

###

# @name logout
POST {{baseUrl}}{{apiPrefix}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name resetPassword
POST {{baseUrl}}{{apiPrefix}}/auth/reset
Content-Type: application/json

{
    "email": "doavers@gmail.com"
}

###

# @name newPassword
POST {{baseUrl}}{{apiPrefix}}/auth/new-password
Content-Type: application/json

{
    "token": "<reset_token>",
    "password": "newpassword123"
}
